### ISSUE TITLE
Load Structure Data

### ISSUE THREAD

**Issue by gtonkinhill** [sa-lee/starmie#2]
A function to load multiple STRUCTURE output files. 

Perhaps we should split this into multiple functions that iteratively add the output of the post processing programs (clump, harvester etc).

Inputs:
Output of STRUCTURE, clump, clumpak? and harvester.

Output:
A useful data frame for further downstream analysis.

**Comment by sa-lee** [comment]
are you thinking something along the lines of
read.structure
read.clumpp
read.clumpak
read.harvester ?

**Comment by sa-lee** [comment]
Looking good Gerry 👍 I'm happy to write a few I/O tests then we should be able to close this.

**Comment by sa-lee** [comment]
got to play around with settings here, like using prior population information and snp datasets with missingness. etc.

**Comment by gtonkinhill** [comment]
Yeah, I think it's probably easiest if we write tests that check the output of loadStructure for each of the tables and then run a bunch of different input  files through it with different parameters. This will save us from having to inspect each result manually.
