### ISSUE TITLE
starmieList object?

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/starmie#20]
Considering most of the utility of our package comes from combining multiple lists of struct objects -  is it worth creating an S3 object that stores multiple Ks/runs?

**Comment by gtonkinhill** [comment]
Would it include additional logic/checks?

**Comment by sa-lee** [comment]
my idea here would be some kind of data structure so people could group their data together in some meaningful way. so for example plotK could just check if something is of type starmieList etc. not sure if it's worth the effort though.

**Comment by sa-lee** [comment]
need to implement some slice methods for subsetting structLists. @gtonkinhill any suggestions for other methods for structLists? also need to implement an admixList object too.
