### ISSUE TITLE
test loadStructure output on other STRUCTURE models

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/starmie#28]
we've tried combinations of
- linkage/no-linkage
  -admixture/no-admixture
- a few others.
- need to see if struct objects are still given sensisble output if main/extraparams change

**Comment by gtonkinhill** [comment]
@sa-lee have we done this now?

**Comment by sa-lee** [comment]
i think so. i'm pretty sure the main issues are fixed. i'll close it now.
