### ISSUE TITLE
Estimate the best K

### ISSUE THREAD

**Issue by gtonkinhill** [sa-lee/starmie#4]
A function that runs the method of Evanno and plots ln(Pr(X|K) values in order to identify the k for which Pr(K=k) is highest (as described in STRUCTURE's manual, section 5.1)

**Comment by sa-lee** [comment]
I also think an interesting possibility would be to pool results from various tools here. Not exactly sure how to go about this at this stage.

**Comment by gtonkinhill** [comment]
clumpak does something like that, although I haven't looked at it yet

**Comment by sa-lee** [comment]
for admixture is this the change point in the CV graph?

**Comment by gtonkinhill** [comment]
I think we can close this now, unless we want to put something in for Admixture?

**Comment by sa-lee** [comment]
looks good. i'll add something in for admixture before closing that uses admixtures cross-validation method to select the min.

**Comment by sa-lee** [comment]
I've added in admixture CV graph. Also throws error if the user hasn't added a log file.

With the repeated runs for STRUCTURE would it be possible to do something akin to https://en.wikipedia.org/wiki/Wilcoxon_signed-rank_test for model selection?

Also I don't know how mathematically sound this would be... but if you're doing repeated structure runs kinda akin to doing a 'bootstrap' like procedure ---> could do likelihood ratio tests?
