### ISSUE TITLE
test datasets

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/starmie#7]
if you have any good example datasets we could use from the output of each of these programs let me know.

**Comment by gtonkinhill** [comment]
How about the last one from here?
[http://pritchardlab.stanford.edu/software/structure-data_v.2.3.1.html]

I can run it today if you like.

**Comment by sa-lee** [comment]
Sure sounds good to me :)

**Comment by sa-lee** [comment]
I've included the admixture test hapmpa3 dataset in inst/extdata too
